// Generated by tools/daodejing/gen_content.py from tools/daodejing/chapters/*.txt.
// Do not edit by hand; edit the chapter source and run the generator.

#include "ddj_text.h"

const ddj_chapter_t ddj_chapters[DDJ_CHAPTER_COUNT] = {
    {
        .number = 1,
        .volume = DDJ_VOLUME_DAO,
        .title = "道可道",
        .passage_first = 0,
        .passage_count = 6,
        .point_first = 0,
        .point_count = 5,
        .option_first = 0,
        .question = "有没有一件事，你越想说清，越说不清？",
    },
};

/* 原文分屏，一屏一句。 */
const char *const ddj_passages[DDJ_PASSAGE_COUNT] = {
    "道可道，非常道。",
    "名可名，非常名。",
    "无名天地之始，有名万物之母。",
    "故常无欲，以观其妙；常有欲，以观其徼。",
    "此两者同出而异名，同谓之玄。",
    "玄之又玄，众妙之门。",
};

/* 要点式点拨，一条一屏。 */
const char *const ddj_points[DDJ_POINT_COUNT] = {
    "开口即失。能说出口的道，已经不是那个道。老子先把你的抓手全拆了，是提醒你：往下只能自己走。",
    "「无名」不是没有名字，是还没被命名的那一片。你一给它起名，它就被框住。留一块没被框住的地方。",
    "「无欲」「有欲」不是褒贬，是两种看法：松开执著看得见微妙，带着目的看得见边界。只用一样就偏。",
    "妙与徼、无与有，本来是一件事的两个面，老子叫它「玄」。到这一层别再站队了——站哪边都是输。",
    "「玄之又玄」不是越绕越晕，是让你放掉已经到手的结论。今天读一遍，他日再读，意思会换。",
};

/* 参究选项，每章三个：槽 0 接了、槽 1 还要想、槽 2 没接上。 */
const char *const ddj_options[DDJ_OPTION_COUNT] = {
    "有。还卡在那儿",
    "有过，后来松了",
    "想不起来，先搁",
};
