// Generated by tools/daodejing/gen_content.py from tools/daodejing/chapters/*.txt.
// Do not edit by hand; edit the chapter source and run the generator.

#pragma once

#include <stdint.h>

/* 全本《道德经》固定 81 章；进度按 81 章存，与已收录多少章无关。 */
#define DDJ_TOTAL_CHAPTERS 81
#define DDJ_DAO_LAST_CHAPTER 37

/* 当前收录的章数，以及为它们展开的原文屏数、点拨条数、选项数。 */
#define DDJ_CHAPTER_COUNT 1
#define DDJ_PASSAGE_COUNT 6
#define DDJ_POINT_COUNT 5
#define DDJ_OPTION_COUNT 3
#define DDJ_PONDER_OPTION_COUNT 3

/* 一层一屏放得下的字数上限。数值来自 content.py，与 240x320 面板的
 * 实际版式对齐（见 content.py 顶部那张对照表）。 */
#define DDJ_PASSAGE_MAX_CHARS 24
#define DDJ_POINT_MAX_CHARS 48
#define DDJ_QUESTION_MAX_CHARS 26
#define DDJ_OPTION_MAX_CHARS 7

typedef enum {
    DDJ_VOLUME_DAO = 0,   /* 道经，第 1 - 37 章 */
    DDJ_VOLUME_DE = 1,    /* 德经，第 38 - 81 章 */
} ddj_volume_t;

/* 一章的全部内容。原文、点拨、选项各自存在平铺的表里，这里只记下标，
 * 这样 81 章共用一套短小的结构体，不会有 N 个指针数组。 */
typedef struct {
    uint8_t number;          /* 章号，从 1 起 */
    ddj_volume_t volume;     /* 道经 / 德经 */
    const char *title;       /* 章题，如「道可道」 */
    uint16_t passage_first;  /* 首屏在 ddj_passages 里的下标 */
    uint8_t passage_count;   /* 本章几屏原文 */
    uint16_t point_first;    /* 首条点拨在 ddj_points 里的下标 */
    uint8_t point_count;     /* 本章几条点拨 */
    uint16_t option_first;   /* 槽 0 在 ddj_options 里的下标，恒为 3 的倍数 */
    const char *question;    /* 参究一问 */
} ddj_chapter_t;

extern const ddj_chapter_t ddj_chapters[DDJ_CHAPTER_COUNT];
extern const char *const ddj_passages[DDJ_PASSAGE_COUNT];
extern const char *const ddj_points[DDJ_POINT_COUNT];
extern const char *const ddj_options[DDJ_OPTION_COUNT];
