// Generated by tools/sanzijing/gen_content.py from tools/sanzijing/sanzijing.txt.
// Do not edit by hand; run the generator instead.
#pragma once

/* One 句 is exactly three CJK characters: 9 UTF-8 bytes plus the NUL. */
#define SZJ_LINE_BYTES 10
#define SZJ_LINES_PER_STANZA 4
#define SZJ_LINE_COUNT 404
#define SZJ_STANZA_COUNT 101
#define SZJ_CJK_CHAR_COUNT 1212

/* Every 句 of the text, in original order. No entry is NULL. */
extern const char *const szj_lines[SZJ_LINE_COUNT];
