#!/usr/bin/env python3
"""Generate ``main/ddj_text.c`` and ``main/ddj_text.h`` from the content sources.

The C tables are a projection of ``tools/daodejing/chapters/*.txt`` and nothing
else: no string is ever edited in C directly. Run from the repository root:

    python3 tools/daodejing/gen_content.py            # (re)write the tables
    python3 tools/daodejing/gen_content.py --check    # fail if they are stale

``--check`` is what CI and ``tools/validate.sh`` use, so a chapter edit that
forgets to regenerate is caught instead of shipping an out-of-date table.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import content  # noqa: E402  (path set up above)

ROOT = Path(__file__).resolve().parents[2]
OUT_C = ROOT / "main" / "ddj_text.c"
OUT_H = ROOT / "main" / "ddj_text.h"

VOLUME_ENUM = {"道经": "DDJ_VOLUME_DAO", "德经": "DDJ_VOLUME_DE"}

HEADER_NOTICE = (
    "// Generated by tools/daodejing/gen_content.py from "
    "tools/daodejing/chapters/*.txt.\n"
    "// Do not edit by hand; edit the chapter source and run the generator.\n"
)


def c_string(text: str) -> str:
    """A C string literal for arbitrary UTF-8 text."""
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def render_header(chapters: tuple[content.Chapter, ...]) -> str:
    passage_total = sum(len(c.passages) for c in chapters)
    point_total = sum(len(c.points) for c in chapters)
    option_total = len(chapters) * content.OPTION_SLOTS

    lines = [
        HEADER_NOTICE,
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "/* 全本《道德经》固定 81 章；进度按 81 章存，与已收录多少章无关。 */",
        f"#define DDJ_TOTAL_CHAPTERS {content.TOTAL_CHAPTERS}",
        f"#define DDJ_DAO_LAST_CHAPTER {content.DAO_VOLUME_LAST_CHAPTER}",
        "",
        "/* 当前收录的章数，以及为它们展开的原文屏数、点拨条数、选项数。 */",
        f"#define DDJ_CHAPTER_COUNT {len(chapters)}",
        f"#define DDJ_PASSAGE_COUNT {passage_total}",
        f"#define DDJ_POINT_COUNT {point_total}",
        f"#define DDJ_OPTION_COUNT {option_total}",
        f"#define DDJ_PONDER_OPTION_COUNT {content.OPTION_SLOTS}",
        "",
        "/* 一条点拨必须一屏放得下，生成阶段按这个上限核对。 */",
        f"#define DDJ_POINT_MAX_CHARS {content.POINT_MAX_CHARS}",
        "",
        "typedef enum {",
        "    DDJ_VOLUME_DAO = 0,   /* 道经，第 1 - 37 章 */",
        "    DDJ_VOLUME_DE = 1,    /* 德经，第 38 - 81 章 */",
        "} ddj_volume_t;",
        "",
        "/* 一章的全部内容。原文、点拨、选项各自存在平铺的表里，这里只记下标，",
        " * 这样 81 章共用一套短小的结构体，不会有 N 个指针数组。 */",
        "typedef struct {",
        "    uint8_t number;          /* 章号，从 1 起 */",
        "    ddj_volume_t volume;     /* 道经 / 德经 */",
        "    const char *title;       /* 章题，如「道可道」 */",
        "    uint16_t passage_first;  /* 首屏在 ddj_passages 里的下标 */",
        "    uint8_t passage_count;   /* 本章几屏原文 */",
        "    uint16_t point_first;    /* 首条点拨在 ddj_points 里的下标 */",
        "    uint8_t point_count;     /* 本章几条点拨 */",
        "    uint16_t option_first;   /* 槽 0 在 ddj_options 里的下标，恒为 3 的倍数 */",
        "    const char *question;    /* 参究一问 */",
        "} ddj_chapter_t;",
        "",
        f"extern const ddj_chapter_t ddj_chapters[DDJ_CHAPTER_COUNT];",
        f"extern const char *const ddj_passages[DDJ_PASSAGE_COUNT];",
        f"extern const char *const ddj_points[DDJ_POINT_COUNT];",
        f"extern const char *const ddj_options[DDJ_OPTION_COUNT];",
        "",
    ]
    return "\n".join(lines)


def render_source(chapters: tuple[content.Chapter, ...]) -> str:
    passages: list[str] = []
    points: list[str] = []
    options: list[str] = []

    chapter_rows: list[str] = []
    for chapter in chapters:
        passage_first = len(passages)
        passages.extend(chapter.passages)
        point_first = len(points)
        points.extend(chapter.points)
        option_first = len(options)
        options.extend(chapter.options)

        chapter_rows.append(
            "    {\n"
            f"        .number = {chapter.number},\n"
            f"        .volume = {VOLUME_ENUM[chapter.volume]},\n"
            f"        .title = {c_string(chapter.title)},\n"
            f"        .passage_first = {passage_first},\n"
            f"        .passage_count = {len(chapter.passages)},\n"
            f"        .point_first = {point_first},\n"
            f"        .point_count = {len(chapter.points)},\n"
            f"        .option_first = {option_first},\n"
            f"        .question = {c_string(chapter.question)},\n"
            "    },"
        )

    lines = [
        HEADER_NOTICE,
        '#include "ddj_text.h"',
        "",
        "const ddj_chapter_t ddj_chapters[DDJ_CHAPTER_COUNT] = {",
        *chapter_rows,
        "};",
        "",
        "/* 原文分屏，一屏一句。 */",
        "const char *const ddj_passages[DDJ_PASSAGE_COUNT] = {",
        *(f"    {c_string(text)}," for text in passages),
        "};",
        "",
        "/* 要点式点拨，一条一屏。 */",
        "const char *const ddj_points[DDJ_POINT_COUNT] = {",
        *(f"    {c_string(text)}," for text in points),
        "};",
        "",
        "/* 参究选项，每章三个：槽 0 接了、槽 1 还要想、槽 2 没接上。 */",
        "const char *const ddj_options[DDJ_OPTION_COUNT] = {",
        *(f"    {c_string(text)}," for text in options),
        "};",
        "",
    ]
    return "\n".join(lines)


def write_or_check(path: Path, text: str, check: bool) -> bool:
    """Write the file, or report whether it is already current."""
    existing = path.read_text(encoding="utf-8") if path.is_file() else None
    if existing == text:
        print(f"unchanged: {path.relative_to(ROOT)}")
        return True
    if check:
        print(f"STALE: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote: {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    try:
        chapters = content.load_chapters()
    except content.ContentError as error:
        print(f"content error: {error}", file=sys.stderr)
        return 1

    passage_total = sum(len(c.passages) for c in chapters)
    point_total = sum(len(c.points) for c in chapters)
    print(
        f"chapters: {len(chapters)}  passages: {passage_total}  "
        f"points: {point_total}  options: {len(chapters) * content.OPTION_SLOTS}"
    )

    ok = write_or_check(OUT_H, render_header(chapters), args.check)
    ok = write_or_check(OUT_C, render_source(chapters), args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
