#!/usr/bin/env python3
"""Generate the application's 三字經 text tables from `sanzijing.txt`.

The text file is the curated source of truth: one 3-character 句 per line,
404 lines in total, grouped into 101 stanzas of four 句 (the classic unit of
four three-character lines). Regenerating after any text edit keeps the C
tables, the character inventory and the font subsets in sync.

Usage (from the repository root):
    python3 tools/sanzijing/gen_content.py [--check]

`--check` verifies the committed C file matches the text file without writing.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TEXT = ROOT / "tools" / "sanzijing" / "sanzijing.txt"
OUT_C = ROOT / "main" / "szj_text.c"
OUT_H = ROOT / "main" / "szj_text.h"

LINES_PER_STANZA = 4
CHARS_PER_LINE = 3

BANNER = (
    "// Generated by tools/sanzijing/gen_content.py from "
    "tools/sanzijing/sanzijing.txt.\n"
    "// Do not edit by hand; run the generator instead.\n"
)


def read_lines() -> list[str]:
    raw = TEXT.read_text(encoding="utf-8")
    lines = [line.strip() for line in raw.splitlines() if line.strip()]
    for index, line in enumerate(lines):
        if len(line) != CHARS_PER_LINE:
            raise SystemExit(
                f"{TEXT}: line {index + 1} has {len(line)} characters, expected {CHARS_PER_LINE}"
            )
        if not all("\u4e00" <= c <= "\u9fff" for c in line):
            raise SystemExit(f"{TEXT}: line {index + 1} has a non-CJK character: {line!r}")
    if len(lines) % LINES_PER_STANZA != 0:
        raise SystemExit(
            f"{TEXT}: {len(lines)} lines is not a multiple of {LINES_PER_STANZA}"
        )
    return lines


def render_header(lines: list[str]) -> str:
    return f"""{BANNER}#pragma once

/* One 句 is exactly three CJK characters: 9 UTF-8 bytes plus the NUL. */
#define SZJ_LINE_BYTES 10
#define SZJ_LINES_PER_STANZA {LINES_PER_STANZA}
#define SZJ_LINE_COUNT {len(lines)}
#define SZJ_STANZA_COUNT {len(lines) // LINES_PER_STANZA}
#define SZJ_CJK_CHAR_COUNT {len(lines) * CHARS_PER_LINE}

/* Every 句 of the text, in original order. No entry is NULL. */
extern const char *const szj_lines[SZJ_LINE_COUNT];
"""


def render_source(lines: list[str]) -> str:
    body = "".join(f'    "{line}",\n' for line in lines)
    return f"""{BANNER}#include "szj_text.h"

const char *const szj_lines[SZJ_LINE_COUNT] = {{
{body}}};
"""


def write_if_changed(path: Path, content: str, check: bool) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        print(f"unchanged: {path.relative_to(ROOT)}")
        return True
    if check:
        print(f"STALE: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote: {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    lines = read_lines()
    print(f"text lines: {len(lines)}  stanzas: {len(lines) // LINES_PER_STANZA}")

    ok = write_if_changed(OUT_H, render_header(lines), args.check)
    ok &= write_if_changed(OUT_C, render_source(lines), args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
